### ISSUE TITLE
[Calendar] Дни недели

### ISSUE THREAD

**Issue by pavel-b-novikov** [miketurch/nsudotnet#1]
```csharp
Console.WriteLine("{0} \t {1} \t {2} \t {3} \t {4} \t {5} \t {6}", 
                    DayOfWeek.Monday.ToString().Remove(2),
                    DayOfWeek.Thursday.ToString().Remove(2),
                    DayOfWeek.Wednesday.ToString().Remove(2),
                    DayOfWeek.Tuesday.ToString().Remove(2),
                    DayOfWeek.Friday.ToString().Remove(2),
                    DayOfWeek.Saturday.ToString().Remove(2),
                    DayOfWeek.Sunday.ToString().Remove(2));
```

Три нюанса: 
* Эта конструкция поддерживает только английские названия дней недели. Можно сделать универсально, на всех языках
* Циклы использовать все-таки сложно, да?
* Зачем вы вообще пошли изучать C#?

**Comment by miketurch** [comment]
Не знаю, почему так решил сделать чего-то
Исправил на массив, в котором можно будет самому задать название дней на все языках и потом в цикле все названия выведутся

**Comment by pavel-b-novikov** [comment]
Нет, это херовое решение. Я его не принимаю. Я рассказывал на лекциях как сделать нормально

**Comment by miketurch** [comment]
В плане плохо, что в массиве хранятся? Или в каком месте плохо и что нужно переделать?

**Comment by pavel-b-novikov** [comment]
Я рассказывал о механизме вывода дат текстом на первых лекциях. Повторять я не намерен.

**Comment by miketurch** [comment]
Так у меня сейчас там нет дат, а просто массив стринговый.
Я не прошу рассказать, какой механизм, а просто узнать хочу, какой именно момент неправильный. 
Неправильно, что название дней недели в массив стринговый завожу?

**Comment by pavel-b-novikov** [comment]
Неправильный момент в том, что вы не знаете о необходимых механизмах блин. 
Окей, я постараюсь быть понятным: неправильный момент в том, что вы в принципе хардкодите имена дней недели.

**Comment by miketurch** [comment]
Можно сделать что-то типа
Console.WriteLine(string.Join(" ", daysNames));
Вместо вывода, который был.
Этот момент неправильный имелся ввиду?

**Comment by pavel-b-novikov** [comment]
Я предлагаю закрыть этот диалог незачетом задачи. Я уже вижу что вас не было на лекции, на которой я показывал что имеется в виду и говорил не хардкодить дни недели. Вы просто не понимаете что от вас требуется.

**Comment by miketurch** [comment]
Но почему?
Изначально у меня они и не были захордкожены, я просто подумал, что раз вы попросили любой язык, то имелось ввиду это, не так понял, видимо.
Сейчас переделал, посмотрите, пожалуйста.
Получаю локальные названия дней недели, чтобы были как раз разные языки, смотря у кого что.
И вывод сделал более оптимальный их, без всяких циклов или копипастов.
Просто не так Вас понял и все вначале, видимо

**Comment by pavel-b-novikov** [comment]
Ай ладно, так уже лучше
