### ISSUE TITLE
[TicTacToe] Циклы

### ISSUE THREAD

**Issue by pavel-b-novikov** [miketurch/nsudotnet#10]
```csharp
public bool Full()
{
 for (int i = 0; i < 9; i++)
 {
  for (int j = 0; j < 9; j++)
  {
   if (!_bigField.SmallFields[i].IsFull())
   {
    return false;
   }
  }
 }

 return true;
}
```

- А давайте мы каждое подполе проверим 9 раз?
- Отличная идея!

Слезайте с MDMA, товарищи

**Comment by miketurch** [comment]
Ой, это случайно, видимо
Исправили

**Comment by kittypr** [comment]
Это вроде я писала -  не знала, как все устроено, и сперва думала, что все ячейки мне вручную проверять, а потом вспомнила, что есть готовый метод, но цикл убрать забыла :С
