### ISSUE TITLE
[TicTacToe] IsWin

### ISSUE THREAD

**Issue by pavel-b-novikov** [miketurch/nsudotnet#11]
Короче так не делается. Один из хороших способов - сформировать из всех ячеек (они у вас идут подряд вроде как) 2хбайтное число (используй сдвиги или бинарное "или") и далее проверить его через бинарное & на соответствие 5 числам в десятичным представлении, у которых на определенном месте стоит бит-единичка. 
Этот подход будет интеллектуальнее чем то, что вы сделали. Вот на него и переделайте

**Comment by miketurch** [comment]
Готово, изменили.
