### ISSUE TITLE
[LinesCounter] Parallel.ForEach

### ISSUE THREAD

**Issue by pavel-b-novikov** [miketurch/nsudotnet#2]
Ну раз пошла такая пьянка, то и уберите ожидание ввода-вывода. А то что ж у вас большая часть ядер ждет пока кусок файла загрузится в буфер. Непорядок.

**Comment by miketurch** [comment]
Изменил немного алгоритм

**Comment by pavel-b-novikov** [comment]
Вы не алгоритм изменили. Вы Parallel убрали, потому что видимо не очень поняли как выполнить задание

**Comment by miketurch** [comment]
Окей, с ним тогда переделаю 
Просто думал можно просто на другое заменить, а то это для этой задачи излишне

**Comment by miketurch** [comment]
Исправил
Сделал неблокирующийся ввод-вывод
