### ISSUE TITLE
[TicTacToe] Зачем вам MVC?

### ISSUE THREAD

**Issue by pavel-b-novikov** [miketurch/nsudotnet#8]
В консольном-то приложении

**Comment by miketurch** [comment]
Просто так показалось удобней будет

**Comment by pavel-b-novikov** [comment]
И в чем выражается удобство? Вы все консольные приложения пишете используя этот паттерн?

**Comment by miketurch** [comment]
Нет 
Удобней просто было разбить кто что делает, в паре так удобней будет работать, показалось

**Comment by kittypr** [comment]
Да, ну и у нас был опыт консольного сапера с мвц, поэтому как-то естественно показалось его использовать и удобно поделить на кусочки.

**Comment by pavel-b-novikov** [comment]
Ладно, шут с вами
